apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aliexpress
  template:
    metadata:
      labels:
        app: aliexpress
    spec:
      containers:
        - name: aliexpress
          image: zakaryab2003/aliexpress:latest
          envFrom:
            - configMapRef:
                name: aliexpress-env